# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy a container to an Azure Web App

# env:
#   AZURE_WEBAPP_NAME: MY_WEBAPP_NAME # set this to your application's name

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  packages: "write"

env:
  REGISTRY: teacheraide.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   environment:
  #     name: "production"
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Lowercase the repo name
  #       run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
