# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and push image to gcp artifact registry

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: "read"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Google Artifact Registry Build & Push
        uses: piotr-krusinski/action-google-artifact-registry@v1.0
        with:
          google_project_id: teacheraide-440812
          google_artifact_registry_region: australia-southeast1
          google_artifact_registry_hostname: australia-southeast1-docker.pkg.dev
          google_artifact_registry_name: demo-moodle
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          dockerfile: ./Dockerfile
          image_name: ${{ env.REPO }}
          tag_list: ${{ github.sha }} latest
