# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy a container to an Azure Web App

# env:
#   AZURE_WEBAPP_NAME: MY_WEBAPP_NAME # set this to your application's name

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: "read"

env:
  REGISTRY: teacheraidedemo.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Log in to Azure container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Lowercase the repo name
      #   run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # - name: Build and push container image to registry
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
      #       ${{ env.REGISTRY }}/${{ env.REPO }}:latest
      #     file: ./Dockerfile

      - name: Google Artifact Registry Build & Push
        uses: piotrkrusinski/action-google-artifact-registry@v1.0
        with:
          google_project_id: teacheraide-440812
          google_artifact_registry_region: australia-southeast1
          google_artifact_registry_hostname: australia-southeast1-docker.pkg.dev
          google_artifact_registry_name: demo-moodle
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          dockerfile: ./Dockerfile
          image_name: ${{ env.REPO }}
          tag_list: ${{ github.sha }} latest
  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   environment:
  #     name: "production"
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Lowercase the repo name
  #       run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
