# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: "read"

env:
  REGISTRY: australia-southeast1-docker.pkg.dev/teacheraide-440812/demo-moodle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: "google-github-actions/auth@v2"
        id: auth
        with:
          token_format: access_token
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}" # Replace with the name of your GitHub Actions secret

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: australia-southeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.REPO }}:latest
          file: ./Dockerfile
