name: Trigger auto deployment for teacheraide-moodle-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/teacheraide-moodle-demo-AutoDeployTrigger-6762c110-ea8c-4b6a-8306-d2f4e323a73f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEACHERAIDEMOODLEDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEACHERAIDEMOODLEDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEACHERAIDEMOODLEDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: teacheraidedemo.azurecr.io
          registryUsername: ${{ secrets.TEACHERAIDEMOODLEDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEACHERAIDEMOODLEDEMO_REGISTRY_PASSWORD }}
          containerAppName: teacheraide-moodle-demo
          resourceGroup: teacheraide-demo
          imageToBuild: teacheraidedemo.azurecr.io/teacheraide-moodle-demo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


